name: NPM Publish

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Test
      run: npm test

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Publish Pre-release to NPM
      if: github.ref == 'refs/heads/main'
      run: |
        git_hash=$(git rev-parse --short HEAD)
        npm version prerelease --preid="rc-${git_hash}" --no-git-tag-version
        npm publish --tag rc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

    - name: Publish Release to NPM
      if: github.event_name == 'release'
      run: |
        npm version ${GITHUB_REF#refs/tags/} --no-git-tag-version
        npm publish --tag latest
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
